import Head from "next/head";
import { Settings } from "../components/Settings";
import { Cages } from "../components/Cages";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cages | Sudoku Tools</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <Cages />
        <div className="fixed bottom-0 py-2">
          <Settings />
        </div>
      </main>
    </>
  );
}
